name: issues control
on: push 
jobs: 
  Tarea1:
   name: tarea 1
   runs-on: ubuntu-latest
   steps:
      - name: create Github Issue
        uses: Deyber13013/create-issue-action@v1
        with:
          title: " Push asociado "
